<?xml version="1.0" encoding="utf-8"?>
<package format="2">
  <name>diff_drive</name>
  <version>1.0.0</version>
  <description>
    This package implements a control mechanism for a differential drive robot.
  </description>
  <author>po54117403-droid</author>
  <maintainer email="po54117403@163.com">Mark Rose</maintainer>
  <url type="website">https://github.com/po54117403-droid/ROS-ROBOT-API</url>
  <url type="repository">https://github.com/po54117403-droid/ROS-ROBOT-API.git</url>
  <url type="bugtracker">https://github.com/po54117403-droid/ROS-ROBOT-API/issues</url>
  <license>BSD</license>
  <buildtool_depend>catkin</buildtool_depend>

  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>actionlib_msgs</depend>
  <build_depend>rostest</build_depend>
  <depend>message_generation</depend>
  
</package>
